### ISSUE TITLE
Copy Clipboard marking disappears after 5-6 seconds

### ISSUE THREAD

**Issue by eyalap** [mac-s-g/react-json-view#169] opened 2018-02-21 06:33 UTC
In the demo here and when I use this component in my code:
1. Select an item to copy with clipboard - See that the icon is checked
2. Wait a few seconds without moving or move (doesn't matter)
3. The check mark disappears.

**Comment by mac-s-g** [comment] 2018-02-21 16:21
Thanks for reporting this. I'll take a look as soon as I can.

**Comment by mac-s-g** [comment] 2018-02-21 17:27
@eyalap the checkmark appears after successfully copying to clipboard.  it's on a timeout, so it disappears after 5.5s.

the source for that is here: https://github.com/mac-s-g/react-json-view/blob/master/src/js/components/CopyToClipboard.js#L43

that timeout is by design; but it sounds like it's not intuitive.  how would you like to see that behavior improve?

**Comment by mac-s-g** [comment] 2018-02-24 19:36
closing this for now because I don't believe there's a bug

**Closed by mac-s-g** 2018-02-24 19:36 UTC
