### ISSUE TITLE
GUI propositions

### ISSUE THREAD

**Issue by hex13** [mac-s-g/react-json-view#91] opened 2017-08-03 21:04 UTC
- when in edit mode I would like a property value to be changed after pressing `return` key (now it's only mouse supported) and to be cancelled after pressing `escape` key.
- I would like also to be able to enter edit mode by double clicking either property key or property value
- how to rename a key of property? ;(
- it would be nice if `tab` key (or arrows, whatever) allowed for navigating between properties

**Comment by hex13** [comment] 2017-08-04 08:41
I wonder maybe it would be even better to enter edit mode by (single) clicking instead of double clicking, as I proposed.

**Comment by mac-s-g** [comment] 2017-08-15 01:53
just posted #96 

that includes the following UX updates:
 * double click value to enter edit mode
 * escape key exits edit mode
 * ctrl+enter submits edit form

I'll update when the updates are committed and published

**Comment by mac-s-g** [comment] 2017-08-15 01:59
I committed and published to [npm with version: 1.12.0](https://www.npmjs.com/package/react-json-view)

The updates aren't exactly to the suggested spec, but i chose to go with dblclick and ctrl+enter after playing with the UI a bit.

I'll leave this issue open to track renaming keys and possibly improving navigation between properties.

**Comment by mac-s-g** [comment] 2017-08-15 02:07
1I updated [the component demo](https://mac-s-g.github.io/react-json-view/demo/) to run rjv 1.12.0

you can test the changes there.

let me know what you think!

**Comment by mac-s-g** [comment] 2017-08-17 18:15
regarding renaming a key:  I was thinking that I could add a click event that pops up the key name modal.

the problem is that clicking keys is already associated with a collapse/expand behavior.

I'm wondering if you have any ideas on how that could work?

**Comment by wintercounter** [comment] 2017-10-03 15:46
> I'm wondering if you have any ideas on how that could work?
With CTRL+Click then?

**Comment by mac-s-g** [comment] 2017-12-22 23:27
closing this issue because most features have been implemented.  feel free to open a new issue with specific feature requests if you feel this one was not completed.

**Closed by mac-s-g** 2017-12-22 23:27 UTC
Labels: feature request
