### ISSUE TITLE
Cannot display array of objects

### ISSUE THREAD

**Issue by naivefun** [mac-s-g/react-json-view#176] opened 2018-03-09 02:30 UTC
Array of primitive type is working fine, but with array of objects it cannot recognize at all.
<img width="501" alt="screen shot 2018-03-09 at 10 26 19 am" src="https://user-images.githubusercontent.com/10683378/37187228-5b5fa982-2384-11e8-80b0-3deecbda8831.png">

```json
{
  "statusCode": "ok",
  "result": {
    "project": {
      "id": "5a94b6441682a0a126dd1538",
      "name": "DocNodes",
      "defaultVersionId": "5a94b6441682a0a126dd1539",
      "versions": [
        {
          "id": "5a94b6441682a0a126dd1539",
          "number": "1.0.0 "
        }
      ]
    },
    "collection": {
      "id": "5a94b6441682a0a126dd1539",
      "projectId": "5a94b6441682a0a126dd1538",
      "mainOutline": {
        "id": "root",
        "name": "root",
        "children": [
          {
            "id": "5a94b6781682a0a126dd153a",
            "name": "Project Overview",
            "children": [],
            "entities": [
              {
                "id": "5a94b68f1682a0a126dd153b",
                "name": "Introduction",
                "type": "Page"
              },
              {
                "id": "5a95169802264c5a6a40e646",
                "name": "Introduction",
                "type": "Page"
              }
            ]
          },
          {
            "id": "5a9518c502264c5a6a40e647",
            "name": "Authentication",
            "children": [],
            "entities": [
              {
                "id": "5a9518db02264c5a6a40e648",
                "name": "Refresh Token",
                "type": "Page"
              },
              {
                "id": "5a9518eb02264c5a6a40e649",
                "name": "Sign Up User",
                "type": "Endpoint"
              }
            ]
          },
          {
            "id": "5a97415b9a8b7320fda20384",
            "name": "This is it",
            "children": [],
            "entities": [
              {
                "id": "5a9741659a8b7320fda20385",
                "name": "Let it go",
                "type": "Page"
              }
            ]
          }
        ],
        "entities": []
      },
      "settings": {
        "environments": [
          {
            "id": "1",
            "name": "development",
            "baseUrl": "http://localhost:8080",
            "envValues": {
              "1": "123",
              "2": "345"
            }
          },
          {
            "id": "2",
            "name": "production",
            "baseUrl": "http://docnodes.com/api",
            "envValues": {
              "r1DPtG5uz": "{{username}}"
            }
          },
          {
            "id": "HJc8YzcdG",
            "name": "staging",
            "baseUrl": "http://docnodes.com/api",
            "envValues": {}
          },
          {
            "id": "HJPhafcdG",
            "name": "测试",
            "baseUrl": "http://docnodes.com/api",
            "envValues": {
              "r1DPtG5uz": "pictureUrl"
            }
          }
        ],
        "globalParams": [
          {
            "id": "1",
            "name": "projectId"
          },
          {
            "id": "2",
            "name": "token"
          },
          {
            "id": "r1DPtG5uz",
            "name": "username"
          },
          {
            "id": "rkiPFG9_G",
            "name": "password"
          },
          {
            "id": "B1ry0M9uz",
            "name": "email"
          }
        ]
      }
    }
  }
}
```

**Comment by mac-s-g** [comment] 2018-03-09 06:51
Thanks for pointing this out! I'll look into it as soon as I can.

**Comment by lemming** [comment] 2018-03-13 11:36
Had the same issue recently when using MobX as Array.isArray for observable array is always false (https://mobx.js.org/best/pitfalls.html#issues-with-decorators).

Judjing by screenshot above looks like `result.collection.mainOutline.children` is not recognized as array as well.

I tried json provided by @naivefun on recent version from master and it looks ok:

![2018-03-13 14-26-43](https://user-images.githubusercontent.com/64609/37339467-cf405df2-26cb-11e8-9dda-91859104b168.png)

**Comment by mac-s-g** [comment] 2018-03-13 16:30
@lemming thank you for checking this out.  

I confirmed what you posted.  If I copy the raw JSON that @naivefun posted, and use it as `src`, RJV appears to render appropriately.

@naivefun is it possible that elements in your `src` object are not observable?

**Comment by mac-s-g** [comment] 2018-03-15 17:31
I'm going to close this for now.  @naivefun let me know if you're still having issues.

**Closed by mac-s-g** 2018-03-15 17:31 UTC
