### ISSUE TITLE
Changing the data forgets the collapsed state

### ISSUE THREAD

**Issue by shawninder** [mac-s-g/react-json-view#71] opened 2017-06-29 19:51 UTC
## Reproducing the bug

1. Get a react json view element with data in it in a default un-collapsed state
2. Collapse the root
3. Change the data source
4. EXPECT data changes but collapsed state remains
5 OBSERVE data changes but collapsed state is not remembered

In english, it seems that changing the data forgets the collapsed state. This makes sence since there is no guarantee the new data has the same keys to collapse on, but if the root is collapsed, changing the data should remember that...

**Comment by mac-s-g** [comment] 2017-06-29 20:57
yea, I agree.  I can get a PR up this weekend.

**Comment by mac-s-g** [comment] 2017-07-10 04:45
I haven't forgotten about this, i just couldn't get to it this weekend.  I should be able to address it soon.

**Comment by shawninder** [comment] 2017-07-10 16:55
No pressure, thanks for putting this on your list :)

**Comment by mac-s-g** [comment] 2017-07-29 21:20
okay, i believe the issue is resolved.

basically, once an expand or collapse action is made by the user, the component takes control of it's collapsed state rather than relying on props.

can you take a look and make sure that the behavior is what you'd expect?

merged with #87 

published to npm with [react-json-view v.1.11.4](https://www.npmjs.com/package/react-json-view)
you can also play around with the demo: https://mac-s-g.github.io/react-json-view/demo/

**Closed by mac-s-g** 2017-07-29 21:20 UTC

**Comment by shawninder** [comment] 2017-08-02 17:00
Hey, I'm kind of busy these days but I will come back to this and test it, probably some time next week but it could be later. Thanks a lot for doing this!

**Comment by shawninder** [comment] 2017-09-07 13:56
Ok, I finally got around to testing this and it's working wonderfully!
