### ISSUE TITLE
"Copy to Clipboard" icon does not work inside a bootstrap modal container 

### ISSUE THREAD

**Issue by MrLeebo** [mac-s-g/react-json-view#131] opened 2017-10-30 17:40 UTC
I built a repro using https://esnextb.in/ but it seems that the site's Save function is currently broken.

Repro: https://gist.github.com/MrLeebo/84a3059a7a33993c34567172ec77698f

1. Go to https://esnextb.in/
2. Copy the "code.js" file into the Code tab
3. Copy the "index.html" file into the HTML tab
4. Package tab should auto-populate but you can check it with the "package.json" file
5. Click the "Copy to clipboard" icon. Clipboard does not change
6. If you remove the Modal and simply render the JsonView like normal, the icon works correctly and the clipboard contains the JSON contents

**Comment by mac-s-g** [comment] 2017-10-30 17:58
thanks for reporting the issue!

I'll try to replicate as soon as I have a chance.

**Comment by mac-s-g** [comment] 2017-12-11 04:03
@MrLeebo would you mind testing with `react-json-view@1.14.0`?  the clipboard code changed a bit and i'm wondering if it impacted this issue.

**Comment by MrLeebo** [comment] 2017-12-11 15:38
@mac-s-g Thanks, but it doesn't seem to have made a difference.

**Comment by stephenshank** [comment] 2017-12-13 19:48
@mac-s-g Thanks for such an awesome project! I am experiencing the same issue. Happy to help if possible.

**Comment by mac-s-g** [comment] 2017-12-27 03:10
updating title because I was able to use copy-to-clipboard when using a semantic-ui modal rather than bootstrap.  I'll dig in to bootstrap a bit.

**Comment by mac-s-g** [comment] 2017-12-27 03:23
also verified that the issue does occur when using a [react-bootstrap](https://github.com/react-bootstrap) modal at versoin 0.31.5

**Comment by mac-s-g** [comment] 2017-12-27 03:54
relevant threads:
1. https://stackoverflow.com/questions/38398070/bootstrap-modal-does-not-work-with-clipboard-js-on-firefox
2. https://stackoverflow.com/questions/46107274/copy-text-to-clipboard-not-working-in-bootstrap-modal-dialog

here is the only solution I can find:
https://github.com/zenorocha/clipboard.js/issues/155#issuecomment-217372642

I hope that helps.  I'm closing this issue because I don't think the problem is coming from this library.  It's a documented issue with bootstrap modals.

**Closed by mac-s-g** 2017-12-27 03:54 UTC

**Comment by vaclav-purchart** [comment] 2018-12-04 13:15
I've found similar issue when using `json-react-view` using `@material-ui`. However there is a simple workaround:

```
	handleCopy = (copy) => {
		navigator.clipboard.writeText(JSON.stringify(copy.src, null, '\t'))
	}

...

	<ReactJsonView enableClipboard={this.handleCopy}>
```

**Comment by KilianB** [comment] 2024-03-26 08:36
> I've found similar issue when using `json-react-view` using `@material-ui`. However there is a simple workaround (at least for Chrome):
> 
> ```
> 	handleCopy = (copy) => {
> 		navigator.clipboard.writeText(JSON.stringify(copy.src, null, '\t'))
> 	}
> 
> ...
> 	<ReactJsonView enableClipboard={this.handleCopy}>
> ```

Inside a Mui model adding `disableEnforceFocus` resolved the issue for me.

````tsx
<Modal disableEnforceFocus>
````

**Comment by tjesposito** [comment] 2024-08-28 21:27
@vaclav-purchart suggestion worked for me! (same issue- copy not working within an MUI Dialog)  👍
