### ISSUE TITLE
Can we optimize the bundle size ?

### ISSUE THREAD

**Issue by RajNandigalla** [mac-s-g/react-json-view#337] opened 2021-02-23 21:16 UTC
I tried using this package, but i noticed page lagging on scroll 
can we decrease bundle size , improve performance ?

**Comment by mac-s-g** [comment] 2021-03-08 01:30
please do.  i'm happy to review a pr that improves bundle size.

closing as duplicate of #104.

**Closed by mac-s-g** 2021-03-08 01:30 UTC
