### ISSUE TITLE
enableClipboard doesn't work

### ISSUE THREAD

**Issue by myangsc** [mac-s-g/react-json-view#161] opened 2018-01-17 00:49 UTC
I have a modal the body contain a reactjson object

<ReactJson
            src={jsonData}
            theme={'monokai'}
            Collapsed={false}
            name={null}
/>

When I l click the copy button, there is no problem, but nothing is really get copied. Do I need to enable other thing in order to make it work, thanks

**Comment by mac-s-g** [comment] 2018-01-17 01:00
@myangsc thanks for reporting.  I'm closing this as a duplicate of #131.  please read through the resolution there for more detail.  

Basically, copy-to-clipboard functionality doesn't work inside of *bootstrap* modals.  it's a known bootstrap bug.  I've tested RJV in non-bootstrap modals to verify the bug is not coming from this package.

**Closed by mac-s-g** 2018-01-17 01:00 UTC

**Comment by myangsc** [comment] 2018-01-17 01:17
thanks

**Comment by myangsc** [comment] 2018-01-17 01:28
react modal can just set enforceFocus={false}

**Comment by mac-s-g** [comment] 2018-01-17 01:32
does that resolve the clipboard issue?

**Comment by jakegavin** [comment] 2019-11-20 01:36
I also ran into this issue with Material UI Dialogs/Modals. `disableEnforceFocus` worked but obviously comes with an accessibility trade off. Calling [`navigator.clipboard.writeText`](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText) in a function passed to `enableClipboard` also worked. 

Thanks for the work you've put into this library!

**Comment by JohnLee-cn** [comment] 2020-07-16 03:50
copy to clipboard not work on Material UI Dialogs/Modals  +1 . Thasnks @jakegavin
